### ISSUE TITLE
add a f***ing home page

### ISSUE THREAD

**Issue by krazyorange13** [JeremySeq/LatinWebsite#1]
# there's no f***ing home page
### emotional damage

Jeremy, write a frontend with Flask. **Just do it** _:nike intensifies:_

**Comment by krazyorange13** [comment]
because Django is too hard

**Comment by mattseq** [comment]
fr fr

**Comment by JeremySeq** [comment]
@Krazy0range you're such a gooner
i wanna use a react frontend and flask backend because flask sucks for frontend because you need to reload to get new information unless you want to request info again in js but that makes shit messy because now the frontend and backend are so fricking interconnected
lets just do a separate backend and frontend its way easier and better

btw i've literally already done something like this and flask ended up turning everything into an absolute nightmare which is why I switched to using react for the frontend hence ProtonMC-Old vs ProtonMC

skill issue you dont know react lol imagine

if you really want to you can write a shitty frontend with flask but react is better

**Comment by krazyorange13** [comment]
bro just run flask with debug=True??? idk i like Flask's simplicity, lets u do some cool stuff easily

but i can learn react it doesn't seem too hard

ur such a goofy goober
start jawmaxxing
no girls 👊
